name: Build and upload assets and index

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v1
      with:
        name: build-${{github.sha}}
        path: build/

  deploy-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build from previous step
      uses: actions/download-artifact@v1
      with:
        name: build-${{github.sha}}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: >-
          --acl public-read --follow-symlinks --delete --cache-control "public, max-age=31536000, immutable"
      env:
        AWS_S3_BUCKET: ${{ secrets.REPO_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
        SOURCE_DIR: 'build-${{github.sha}}'
        DEST_DIR: 'assets/${{github.sha}}'

  deploy-test:
    needs: deploy-assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run deploy -- --sha ${{github.sha}}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --cache-control no-store
      env:
        AWS_S3_BUCKET: ${{ secrets.TEST_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
        SOURCE_DIR: 'server/'
