name: Deploy version to production

on:
  repository_dispatch:
    types: trigger-production

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: >-
        npm run build-index --
        --sha ${{github.sha}}
        --environment prod
        --url http://d141os3smnxory.cloudfront.net
    - uses: actions/upload-artifact@v1
      with:
        name: index-${{github.sha}}
        path: server/
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --cache-control no-store
      env:
        AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
        SOURCE_DIR: 'server/'
